### ISSUE TITLE
Integrals not compatible with ForwardDiff (Turing)

### ISSUE THREAD

**Issue by astro-kevin** [SciML/Integrals.jl#108]
When running an integral from numbers propagated from Turing using ForwardDiff, I get the following error:

```
StackOverflowError:

Stacktrace:
 [1] cachedrule(#unused#::Type{ForwardDiff.Dual{ForwardDiff.Tag{Turing.TuringTag, Float64}, Float64, 9}}, n::Int64) (repeats 79984 times)
   @ QuadGK ~/.julia/packages/QuadGK/buWps/src/gausskronrod.jl:253
```

Is this module not compatible with Turing?

**Comment by ChrisRackauckas** [comment]
It's ForwardDiff compatible. What did you run? It would be good to have an MWE of what you're trying to differentiate. 

FWIW, here's what's tested with autodiff: https://github.com/SciML/Integrals.jl/blob/master/test/derivative_tests.jl

If we can learn what case we missed then we can fix it.

**Comment by astro-kevin** [comment]
I'm not sure how to create a MWE of my code because I'm not sure how much of it will still work after I strip out the non-pertinent sections. But I'll try. 

The code that errors is 

```
function dNdr(r, p)
    Mass, zmin, zmax = p[1], p[2], p[3]
    α = 0.133
    β = -1.995
    γ = 0.263
    η = 0.0993
    A = 0.0104
    r̄ = 0.00972
    zfac = ((1+zmax)^(η+1) - (1+zmin)^(η+1))/(1+η)
    Nm = A * (Mass*1e-12)^α * r^β * exp((r/r̄)^γ) * zfac
    return Nm
end

function intdNdr(Mass, zmin, zmax, rmin, rmax)
    prob = IntegraleProblem(dNdr,rmin,rmax, [Mass, zmin, zmax])
    sol = solve(prob, QuadGKJL(), reltol=1e-4)
    return sol
end



function MdNdr(r, p)
    Mass, zmin, zmax = p[1], p[2], p[3]
    α = 0.133
    β = -1.995
    γ = 0.263
    η = 0.0993
    A = 0.0104
    r̄ = 0.00972
    zfac = ((1+zmax)^(η+1) - (1+zmin)^(η+1))/(1+η)
    Mz = A * Mass * (Mass*1e-12)^α * r^(β+1) * exp((r/r̄)^γ) * zfac
    return Mz
end
    
function intMdNdr(Mass, zmin, zmax, rmin, rmax)
    prob = IntegralProblem(MdNdr,rmin,rmax, [Mass, zmin, zmax])
    sol = solve(prob, QuadGKJL(), reltol=1e-4)
    return sol
end
```

From Turing, the parameter which needs to be differentiated is a 9-dimensional vector `parameters`. 

These are passed into my custom code which is basically a forward propagator where some quantity `x[i+1]` depends on `x[I]`. `η` is created by a function of a few of the elements of the vector `parameters`. Mass an iterative quantity like this, and each element is the sum of the previous element with some function wrapping the integral `intdNdr`. Something like

```
function find dM(Mass, zmin, zmax, rmin, rmax)
    zmin and zmax come from another propagated value 
    rmin depends on Mass[begin]
    rmax is a constant
    dM = do continuous math (intMdNdr(Mass, zmin, zmax, rmin, rmax))
```

and `Mass[I+1] = Mass[i]+ dM(Mass, zmin, zmax, rmin, rmax)`

I've been told that perhaps its easier to make a custom rule to implement the fundamental theorem of calculus, but I don't quite see how that applies. 

Thanks

**Comment by ChrisRackauckas** [comment]
This was a downstream issue fixed by https://github.com/JuliaMath/QuadGK.jl/pull/61
