### ISSUE TITLE
Adaptive Quasi-Monte Carlo

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/Integrals.jl#11]
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.127.8178&rep=rep1&type=pdf

I want it.

**Comment by ArnoStrouwen** [comment]
The link is dead, but are MISER, VEGAS etc not adaptive QMC?

**Comment by ChrisRackauckas** [comment]
<html>
<body>


Vegas | Sobol quasi-random sampleor Mersenne Twister pseudo-random sampleor Ranlux pseudo-random sample | Monte CarloMonte CarloMonte Carlo | importance sampling
-- | -- | -- | --
Suave | Sobol quasi-random sampleor Mersenne Twister pseudo-random sampleor Ranlux pseudo-random sample | Monte CarloMonte CarloMonte Carlo | globally adaptive subdivision    + importance sampling
Divonne | Korobov quasi-random sampleor Sobol quasi-random sampleor Mersenne Twister pseudo-random sampleor Ranlux pseudo-random sampleor cubature rules | Monte CarloMonte CarloMonte CarloMonte Carlodeterministic | stratified sampling,    aided by methods from    numerical optimization
Cuhre | cubature rules | deterministic | globally adaptive subdivision


</body>
</html>

Indeed the Cuba methods are.
