### ISSUE TITLE
keyword arguments passed to specific solvers

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/Integrals.jl#135]
Currently, some keywords specific to each cubature method have to be passed as a keyword to solve, while others are present in the struct for the solver algorithm.

I would prefer if all the algorithm specific things become fields in the struct of that algorithm and that we error on anything but a few common keywords, similar to how it works for differential equations.

**Comment by ChrisRackauckas** [comment]
Agreed

**Comment by agerlach** [comment]
What is the status of this? This looks like it was implemened, at least for CUBA but was never released? https://github.com/SciML/Integrals.jl/commit/e7df9ea532a092d2a3fd0cfafd1d1372c6fcc7ed

**Comment by agerlach** [comment]
It looks like the current release of IntegralsCuba (v0.2.2) still supports passing alg specific keywords as kwargs in solve however, the kwarg check in Integrals solve is preventing its usage. Can this get released?

**Comment by ChrisRackauckas** [comment]
I set a release, v0.3.0, let me know if that doesn't work in about half an hour.

**Comment by agerlach** [comment]
It looks like IntegralCubature has the same issue. Can you make a release?
