### ISSUE TITLE
Integrals with lb > ub

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/Integrals.jl#141]
Similar to how `Inf` bounds are handled, we should handle this case by an automatic transformation.
Particularly because the `Inf` bound handling implicitly assumes that `lb < ub`, and integrals from `+inf` to `a` might give incorrect results.

**Comment by ygol55** [comment]
I'm pretty sure that's not supported for a reason, while I couldn't found cases where the lower bound is higher then the higher bound. I guess that's just isn't needed.

**Comment by ygol55** [comment]
I'm pretty sure that's not supported for a reason, while I couldn't found cases where the lower bound is higher then the higher bound. I guess that's just isn't needed (meaning for infinite positive lower bound).
