### ISSUE TITLE
Solving coupled system of linear Volterra integral equations of the second kind

### ISSUE THREAD

**Issue by timmyfaraday** [SciML/Integrals.jl#166]
Hi, 

I'm trying to solve a coupled system of linear Volterra integral equations of the second kind `h1(t)` and `h2(t)` as part of solving a semi-Markov problem, to determine state probabilities `p1(t)` and `p2(t)`. In this light, I've tried to use Integrals.jl, but I'm running into a StackOverflowError. 

Is there any fix to avoid this? Or is the package Integrals.jl not suited for solving this type of problems? Below you may find a 'working' example.

Thanks in advance for your time and effort!

```julia
using Distributions, Integrals

# state 1
D₁₂     = Exponential(2.0)
f₁₂(φ)  = pdf(D₁₂, φ)
F₁(φ)   = cdf(D₁₂, φ)

# state 2
D₂₁     = Exponential(1.0)
f₂₁(φ)  = pdf(D₂₁, φ)
F₂(φ)   = cdf(D₂₁, φ)

# transition frequency densities
h₁(t) = solve(IntegralProblem((τ, p) -> f₂₁(t-τ) .* h₂.(τ), 0.0, t), QuadGKJL()).u
h₂(t) = solve(IntegralProblem((τ, p) -> f₁₂(t-τ) .* h₁.(τ), 0.0, t), QuadGKJL()).u .+ f₁₂.(t)

# state probabilities
p₁(t) = solve(IntegralProblem((τ, p) -> h₁.(τ) * F₁(t-τ), 0.0, t), QuadGKJL()).u .+ F₁(t) 
p₂(t) = solve(IntegralProblem((τ, p) -> h₂.(τ) * F₂(t-τ), 0.0, t), QuadGKJL()).u

p₁(1.0)
```

**Comment by ChrisRackauckas** [comment]
This kind of equation needs to use a Delay Differential Equation solver. A purely explicit integral solver cannot solve such equations. Check the DDE solver documentation for details on how to use it. In that solver, `h(p,t)` is a fully continuous object is continuous object with all of the past history, and you can use Integrals.jl inside of the DDE.
