### ISSUE TITLE
Quadrature routines for pre-sampled data

### ISSUE THREAD

**Issue by IlianPihlajamaa** [SciML/Integrals.jl#170]
Hello, 

thanks for a great package! 

I don't know if this is the right place to ask this question, but:

Are there plans for SciML to offer quadrature routines for pre-sampled data (where one either does not have the luxury of choosing the grid points at all, or at least not dynamically/adaptively? Right now this functionality is scattered throughout the Julia ecosystem (see eg [NumericalIntegration.jl](https://github.com/dextorious/NumericalIntegration.jl), [Romberg.jl](https://github.com/fgasdia/Romberg.jl), [Trapz.jl](https://github.com/francescoalemanno/Trapz.jl)), even though I think this is a fairly common use case.  For reference, there is an excellent python package [QuadPy](https://pypi.org/project/quadpy/), that inspiration might be drawn from, even though it does not offer functionality for arbitrary grids. [SciPy](https://docs.scipy.org/doc/scipy/tutorial/integrate.html#integrating-using-samples) of course does offer that. 

I am asking this, because right now, I am typically rolling my own (eg irregular Simpson's) rules, and I thought that if many people do the same, it might be a waste of effort.

**Comment by ChrisRackauckas** [comment]
I think it would be great to add these kinds of methods, even non-adaptive, to here. They are widely used methods to approximate integrals, so there is no reason to leave them out.

**Comment by IlianPihlajamaa** [comment]
Okay, I might try to do that (for some simple rules like trapezoidal/Simpson's). No promises when though. I may also need some guidance adhering to the code structure and API that this package, together with SciML, dictates.  

Would you like me to close this issue in the meantime?

**Comment by ChrisRackauckas** [comment]
Let's leave this open until they are implemented.
