### ISSUE TITLE
It would be nice to have a `progress` keyword for time estimation

### ISSUE THREAD

**Issue by Yaraslaut** [SciML/Integrals.jl#172]
It would be great to have a progress bar similar to `DifferentialEquations`  https://docs.sciml.ai/DiffEqDocs/stable/features/progress_bar

Also, if this can be easily transferred from `DifferentialEquations` i can try to make PR for this.

**Comment by ChrisRackauckas** [comment]
It's a bit more difficult in this case because it's not clear how to measure the progress, since it's a convergence criteria not stepping across time and thus there's no clear percentage of the computation already done.

**Comment by Yaraslaut** [comment]
We can show percentage of convergence reached for both `abstol` and `reltol` separately, in such way user have some idea of what is happening and can estimate time for integration to complete.

**Comment by Yaraslaut** [comment]
> That is a cool idea! Unfortunately, the libraries that Integrals.jl wraps do not support callbacks that would allow for this kind query of the estimated error. If your integrals take very long to converge, is there a better algorithm that could integrate them with fewer function evaluations?

I am using `CubatureJLh()` i tried also `VEGAS` but performance was not that great since I dont have big dimensions, only two, and need to integrate vectors, if you have any recomendation i am happy to try them out :) 

Closing issue as can not be implemented.

**Comment by Yaraslaut** [comment]
> @Yaraslaut In 2D I would recommend a quadrature or cubature for faster convergence. Other than that, the optimal algorithm will depend on your integrand. If it is very smooth, `CubatureJLp()` would be favorable, since it reuses function evaluations. However if you tried `CubatureJLh()` this would be because your integrand is localized somewhere. If it is localized around points, I would recommend `CubatureJLh()`. However, if it is localized around curves, then doing nested 1d integration will have better computational complexity because of the number of cubes versus intervals it takes to adaptively tile a nearly singular surface in many versus one dimension. The `quadgk!` routine may be your friend in the case of curves.

Thanks for pointing out to some usefull places, I will definitely try to use `quadgk!`
One of the drawbacks i see in it is the lack of parallel computing especially in the nested case
