### ISSUE TITLE
Missing documentation for IntegralFunction and BatchIntegralFunction

### ISSUE THREAD

**Issue by LauravandenBremen** [SciML/Integrals.jl#218]
The tutorial in the documentation for Intergral.jl recommends the use of the “nout” and “batch” keywords which are deprecated. When using these, a warning is given and it is recommended to use IntegralFunction and BatchIntegralFunction instead. There is, however, no documentation on how to use Integral function and BatchIntegralFunction.

I would recommend that the use of “nout” and “batch” be removed from the tutorial in the documentation of Integral.jl and that a example for how to use IntegralFunction and BatchIntegralFunction is added instead. 

This is the first time I report an Issue likt this so I hope I did it correctly, if I did not please let me know. Below a link to discourse on the subject on the Julia forum. https://discourse.julialang.org/t/is-there-any-documentation-on-integralfunctions/108970

**Comment by ChrisRackauckas** [comment]
Generally the docstrings are kept with the types, and those are all separate from the solvers for deps reasons.
