### ISSUE TITLE
Strange instalation or upgrade error 

### ISSUE THREAD

**Issue by milen-prg** [SciML/Integrals.jl#247]
I'm new with Julia, please help me with this:
(Windows 11 Pro 64bit, Julia 1.10.2):

(@v1.10) pkg> update
    Updating registry at `C:\Users\User\.julia\registries\General.toml`
   Installed Missings ──────────── v1.2.0
   Installed FreeTypeAbstraction ─ v0.10.3
   Installed ColorTypes ────────── v0.11.5
   Installed JuliaFormatter ────── v1.0.55
   Installed TaylorIntegration ─── v0.15.2
    Updating `C:\Users\User\.julia\environments\v1.10\Project.toml`
  [92b13dbe] ↑ TaylorIntegration v0.15.1 ⇒ v0.15.2
    Updating `C:\Users\User\.julia\environments\v1.10\Manifest.toml`
  [3da002f7] ↑ ColorTypes v0.11.4 ⇒ v0.11.5
  [663a7486] ↑ FreeTypeAbstraction v0.10.2 ⇒ v0.10.3
  [98e50ef6] ↑ JuliaFormatter v1.0.54 ⇒ v1.0.55
  [e1d29d7a] ↑ Missings v1.1.0 ⇒ v1.2.0
  [92b13dbe] ↑ TaylorIntegration v0.15.1 ⇒ v0.15.2
Precompiling project...
  ? Integrals
  ? Integrals → IntegralsForwardDiffExt
  ? Integrals → IntegralsZygoteExt
  80 dependencies successfully precompiled in 119 seconds. 563 already precompiled.
  3 dependencies failed but may be precompilable after restarting julia
  6 dependencies had output during precompilation:
┌ DiffEqBase → DiffEqBaseDistributionsExt
│  [pid 14076] waiting for IO to finish:
│   Handle type        uv_handle_t->data
│   fs_event           000001d377704c40->000001d37a2795a0
│   timer              000001d37bfdd020->000001d37a2795d0
│  This means that a package has started a background task or event source that has not finished running. For precompilation to complete successfully, the event source needs to be closed explicitly. See the developer documentation on fixing precompilation hangs for more help.
└
┌ Integrals
│  WARNING: Method definition solve(SciMLBase.IntegralProblem{isinplace, P, F, B, K} where K where B where F where P where isinplace) in module Integrals at C:\Users\User\.julia\packages\Integrals\leYds\src\Integrals.jl:60 overwritten at C:\Users\User\.julia\packages\Integrals\leYds\src\Integrals.jl:111.
│  ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
└
┌ Integrals → IntegralsForwardDiffExt
│  WARNING: Method definition solve(SciMLBase.IntegralProblem{isinplace, P, F, B, K} where K where B where F where P where isinplace) in module Integrals at C:\Users\User\.julia\packages\Integrals\leYds\src\Integrals.jl:60 overwritten at C:\Users\User\.julia\packages\Integrals\leYds\src\Integrals.jl:111.
│  ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
└
┌ ModelingToolkit
│  WARNING: using OrdinaryDiffEq.isconstant in module ModelingToolkit conflicts with an existing identifier.
│  WARNING: using OrdinaryDiffEq.islinear in module ModelingToolkit conflicts with an existing identifier.
└
┌ DataDrivenSparse
│  WARNING: method definition for _set! at C:\Users\User\.julia\packages\DataDrivenSparse\0c4Fb\src\DataDrivenSparse.jl:28 declares type variable T but does not use it.
└
┌ Integrals → IntegralsZygoteExt
│  WARNING: Method definition solve(SciMLBase.IntegralProblem{isinplace, P, F, B, K} where K where B where F where P where isinplace) in module Integrals at C:\Users\User\.julia\packages\Integrals\leYds\src\Integrals.jl:60 overwritten at C:\Users\User\.julia\packages\Integrals\leYds\src\Integrals.jl:111.
│  ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
└

(@v1.10) pkg>

(@v1.10) pkg> status
Status `C:\Users\User\.julia\environments\v1.10\Project.toml`
  [5c4adb95] AstroAngles v0.1.3
  [59872b50] AstroConstants v0.1.0
  [c7932e45] AstroLib v0.4.2
  [c61b5328] AstroTime v0.7.0
  [1537fe66] CALCEPH v1.2.0
  [54e8752a] CalcephEphemeris v1.2.0
  [49dc2e85] Calculus v0.5.1
⌃ [2445eb08] DataDrivenDiffEq v1.3.0
  [82cc6244] DataInterpolations v4.7.1
⌅ [459566f4] DiffEqCallbacks v2.29.1
  [071ae1c0] DiffEqGPU v3.4.1
  [055956cb] DiffEqPhysics v3.12.0
  [e0ca9c66] DifferenceEquations v0.5.3
⌃ [0c46a032] DifferentialEquations v7.10.0
  [fa6b7ba4] DualNumbers v0.6.8
  [6a9c3322] Ephemerides v1.2.1
  [6a86dc24] FiniteDiff v2.23.0
  [26cc04aa] FiniteDifferences v0.12.31
  [e9467ef8] GLMakie v0.9.10
  [c91e804a] Gadfly v1.4.0
  [5c1252a2] GeometryBasics v0.4.10
⌃ [de52edbc] Integrals v3.6.0
  [3587e190] InverseFunctions v0.1.13
⌃ [7ed4a6bd] LinearSolve v2.10.0
  [ae8d54c2] Luxor v3.8.0
  [b8f27783] MathOptInterface v1.27.1
  [eff96d63] Measurements v2.11.0
⌅ [961ee093] ModelingToolkit v8.70.0
⌅ [8913a72c] NonlinearSolve v1.10.1
  [c030b06c] ODE v2.15.0
  [77e91f04] OptimKit v0.3.1
⌃ [7f7a1694] Optimization v3.19.3
⌃ [1dea7af3] OrdinaryDiffEq v6.58.2
  [d83715d0] PlanetaryEphemeris v0.8.3
⌃ [ddf597a6] PolyJuMP v0.7.1
  [aea7be01] PrecompileTools v1.2.1
  [308eb6b3] RationalRoots v0.2.1
  [681baf3e] Raylib v0.2.0
  [37e2e3b7] ReverseDiff v1.15.1
  [30cb0354] SciMLTutorials v1.0.0
  [505e40e9] SciPyDiffEq v0.2.1
  [b5612192] SolverTools v0.8.8
  [47a9eef4] SparseDiffTools v2.17.0
  [78aadeae] SymbolicNumericIntegration v1.3.2
⌃ [0c5d862f] Symbolics v5.11.0
  [b36ab563] TaylorDiff v0.2.1
  [92b13dbe] TaylorIntegration v0.15.2
  [6aa5eb33] TaylorSeries v0.17.4
  [07d1fe3e] TensorKit v0.12.2
  [6aa20fa7] TensorOperations v4.1.0
  [9c690861] TensorToolbox v1.0.1
  [2e59a628] Transits v0.4.0
Info Packages marked with ⌃ and ⌅ have new versions available. Those with ⌃ may be upgradable, but those with ⌅ are restricted by compatibility constraints from upgrading. To see why use `status --outdated`

(@v1.10) pkg>

**Comment by ChrisRackauckas** [comment]
Clean your environment. You have something that's making all of your SciML packages require a much older version. Since I don't know all of your packages it's hard to know what it would be, but I would remove things like SolverTools, SciMLTutorials, ... until you can actually upgrade things to the latest. I highly recommend you use environments for your packages.

Closing as there isn't anything to fix here, but please feel free to continue asking questions here or on discourse.julialang.org about fixing your global environment.

**Comment by milen-prg** [comment]
Thank you, because you point where to search. The problem was this packet:
[Transits](https://github.com/JuliaAstro/Transits.jl)
