### ISSUE TITLE
Document parameter usage

### ISSUE THREAD

**Issue by fonsp** [SciML/Integrals.jl#256]
**Question❓**

Hi! Beginner question:

In the documentation I cannot find how to use `p`, the parameter argument. There is one example in the README where `p` is a number, but how can I give more than one number? Can `p` be a named tuple? It might be nice to document this in https://docs.sciml.ai/Integrals/stable/basics/IntegralProblem/

**Comment by ChrisRackauckas** [comment]
`p` can be any Julia type. If you need to autodiff then it needs to be an autodiff-able container type, so basically an Array (or ComponentArray etc.). But there's no restriction on the type of `p` for a forward pass.
