### ISSUE TITLE
Zygote w/ nout > 1 and Batch errors

### ISSUE THREAD

**Issue by agerlach** [SciML/Integrals.jl#40]
Currently not working. See various commented out tests, e.g.
https://github.com/SciML/Quadrature.jl/blob/2fa4a7d10e213a1206f759310264b411b304e731/test/derivative_tests.jl#L153

**Comment by ChrisRackauckas** [comment]
@lxvm you said the PR fixed these, did you try the tests? Maybe we can just uncomment them?

**Comment by ChrisRackauckas** [comment]
I see, so this can close. I'll mark the others as broken. In general it's just not good to have tests commented out and instead they should be `@test_broken` anyways, since that will let you know if they unbreak.
