### ISSUE TITLE
CubaVegas, CubaSUAVE, CubaDivonne: Julia has exited 

### ISSUE THREAD

**Issue by KirillZubov** [SciML/Integrals.jl#47]
For small values of `abstol`, `reltol`, `maxiters`, we get the exit error in `solve` for CubaVegas, CubaSUAVE, CubaDivonne.

```julia
using Quadrature, Cuba

f(x,p) = sum(sin.(x .* p))
lb = ones(2)
ub = 3ones(2)
p = [1.5,2.0]

prob = QuadratureProblem(f,lb,ub,p)
algs = [CubaVegas(), CubaSUAVE(), CubaDivonne()]

for alg in algs
    solve(prob,alg,reltol=1e-4,abstol=1e-4, maxiters =200)[1]
end
#Julia has exited.
```

**Comment by ChrisRackauckas** [comment]
Can you reproduce this with pure Cuba.jl?

**Comment by ArnoStrouwen** [comment]
I think we handle this with https://github.com/SciML/Integrals.jl/pull/124
Something goes wrong with cuba when the number of iters is too low?
@KirillZubov you might want to report this to Cuba.jl since we can't fix this here.
