### ISSUE TITLE
FastGaussQuadrature.jl support?

### ISSUE THREAD

**Issue by oxinabox** [SciML/Integrals.jl#48]
I was looking though quadrature libraries and spotted https://github.com/JuliaApproximation/FastGaussQuadrature.jl

It might be nice to also hook that up to this interface.
(I don't actually have any need for this, was just speculating)

**Comment by YingboMa** [comment]
FastGaussQuadrature.jl just gives quadrature nodes and weights. I am not sure what kind of interface we can add to bridge with FastGaussQuadrature.jl

**Comment by ChrisRackauckas** [comment]
We could, but it's not adaptive so it's hard. The user would have to supply the number of nodes, and we could then do the calculation, but that wouldn't guarantee a tolerance like the other methods.
