### ISSUE TITLE
Additional keyword arguments are not passed to `Hcubature`

### ISSUE THREAD

**Issue by scheidan** [SciML/Integrals.jl#51]
Additional keyword arguments seem to be not passed to `Hcubature`.

In the example below I try to pass `maxevals=typemax(Int)` and `initdiv=50`, however, if used via the `Quadrature.jl` interface they have no effect. 

```Julia
# Aim: \int _infty^infty exp(rosenbrock(x)) dx
rosenbrock(x) = -400*(8*x[1]^2 - x[2] - 0.5)^2 - (4*x[1] - 1)^2

# change of variable
f(t) = exp(rosenbrock(t./(1 .- t.^2))) * prod((1 .+ t.^2)/(1 .- t.^2).^2)

# Quadrature.jl
prob = QuadratureProblem((t,p) -> f(t), -ones(2), ones(2))
int1 = solve(prob, HCubatureJL(),
             reltol=1e-9, abstol=0,
             maxevals=typemax(Int), initdiv=50)

# HCubature.jl
int2 = HCubature.hcubature(f, -ones(2), ones(2),
                           rtol=1e-9, atol=0,
                           maxevals=typemax(Int), initdiv=50)

int1.u ≈ int2[1]  # substantially different!
```
Without the additional keyword arguments, both interface give the same result.

**Comment by ChrisRackauckas** [comment]
We just need a bit more documentation. It should be `maxiters` for all backends.

**Comment by scheidan** [comment]
I don't think that's the problem here.
The ignored parameter `initdiv` is specific to Hcubature and is different from `maxiters`.

Or is there a generic parameter from `Quadrature` that correspond to `initdiv`?

**Comment by scheidan** [comment]
The problem is located at Line 187-193: https://github.com/SciML/Quadrature.jl/blob/master/src/Quadrature.jl#L187

The `kwargs` are not passed to `hcubature` and the argument `initdiv=1` is hard-coded.

**Comment by ChrisRackauckas** [comment]
I see, thanks for finding that. Could you follow up with a quick PR?
