### ISSUE TITLE
batch with scalar bounds

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/Integrals.jl#78]
From the documentation:

_batch: The preferred number of points to batch. This allows user-side parallelization of the integrand. If batch != 0, then each x[:,i] is a different point of the integral to calculate, and the output should be nout x batchsize. Note that batch is a suggestion for the number of points, and it is not necessarily true that batch is the same as batchsize in all algorithms._

That is not true for scalar bounds
```jl
using Quadrature
using Cubature
function f(x,p)
    x
end
function f_batched( dx_batched,x_batched,p)
    for i in 1:size(x_batched,1)
        dx_batched[i] = f(x_batched[i],p)
    end
    return nothing
end
prob = QuadratureProblem(f_batched,0.0,1.0,nout=1,batch=2)
sol = solve(prob,CubatureJLh(),reltol=1e-3,abstol=1e-3)
```

**Comment by ChrisRackauckas** [comment]
Ahh yeah, `x[i]` for scalar.

**Comment by ArnoStrouwen** [comment]
This is now properly documented.
