### ISSUE TITLE
eliminate need for nout parameter in most cases?

### ISSUE THREAD

**Issue by stevengj** [SciML/Integrals.jl#86]
> `nout`: The output size of the function f. Defaults to 1, i.e., a scalar integral output.

It seems like this `nout` parameter should not be needed for all algorithms.

In QuadGK and HCubature, you can integrate functions whose output is in any normed vector space, and the type is deteremined the first time the integrand is evaluated.

I get why you might need `nout` for some of the external C libraries, but it seems like you should be able to tell the user that it is not needed for certain algorithms.

**Comment by ChrisRackauckas** [comment]
This was eliminated in the new API
